### ISSUE TITLE
Any help running flowblade with docker?

### ISSUE THREAD

**Issue by ovizii** [jliljebl/flowblade-forum#117]
I would like to run flowblade in a docker container and access it remotely. To do this, I usually use this baseimage: https://github.com/jlesage/docker-baseimage-gui/ with several other apps. 

The problem is, I used the Debian Buster base image and my Dockerfile build gets stuck at:

```
The following packages have unmet dependencies:
 flowblade : Depends: python3-mlt but it is not installable
E: Unable to correct problems, you have held broken packages.

```

The other available base images is based upon Ubuntu 18.04 but apparently that has problems with flowblade too. 

Any solutions or hints?

**Comment by ovizii** [comment]
I eventually resorted to using

`apt-get install -y flowblade`

knowing it'll give me an older flowblade version. to be more precise about 2.5 years older than the current version :-(

unfortunately that didn't work either, I am seeign this error:

```
flowblade    | [app] starting flowblade...
flowblade    | FLOWBLADE MOVIE EDITOR 2.0
flowblade    | --------------------------
flowblade    | Launch script dir: /usr/bin
flowblade    | Running from installation...
flowblade    | modules path: /usr/share/flowblade/Flowblade
flowblade    | MLT found, version: 6.12.0
flowblade    | numpy version: 1.16.2
flowblade    | Application version: 2.0.0
flowblade    | OS: Debian GNU/Linux 10 (buster)
flowblade    | Python 2.7.16 (default, Oct 10 2019, 22:02:15)
flowblade    | [GCC 8.3.0]
flowblade    | GTK+ version: 3.24.5
flowblade    | User dir:
flowblade    | /.flowblade/
flowblade    | Traceback (most recent call last):
flowblade    |   File "/usr/bin/flowblade", line 91, in <module>
flowblade    |     app.main(modules_path)
flowblade    |   File "/usr/share/flowblade/Flowblade/app.py", line 171, in main
flowblade    |     os.mkdir(user_dir)
flowblade    | OSError: [Errno 2] No such file or directory: '\n/.flowblade/'

```

Any hint would be much appreciated.

**Comment by jliljebl** [comment]
Unfortunately as lead developer I don't have any info achieving this. I'm leaving this open so that if someone comes up with a solution, I hope they will share info here.

**Comment by ovizii** [comment]
thanks for taking note. I might give it another try or find someone to help me figure it out and will update my ticket if I figure it out.
