### ISSUE TITLE
Flowblade won't start

### ISSUE THREAD

**Issue by kurtrisser** [jliljebl/flowblade-forum#52]
I have been happily using Flowblade all week under Fedora 31, but today it refuses to start:

Traceback (most recent call last):
  File "/usr/bin/flowblade", line 94, in <module>
    app.main(modules_path)
  File "/usr/lib/python3.7/site-packages/Flowblade/app.py", line 276, in main
    create_gui()
  File "/usr/lib/python3.7/site-packages/Flowblade/app.py", line 431, in create_gui
    tlinewidgets.load_icons()
  File "/usr/lib/python3.7/site-packages/Flowblade/tlinewidgets.py", line 347, in load_icons
    COMPOSITOR_ICON = guiutils.get_cairo_image("compositor_icon")
  File "/usr/lib/python3.7/site-packages/Flowblade/guiutils.py", line 165, in get_cairo_image
    return cairo.ImageSurface.create_from_png(respaths.IMAGE_PATH + img_name + suffix)
cairo.Error: file not found

Does anyone have suggestions about how to fix this?
Thank you.

**Comment by jliljebl** [comment]
Unfortunately we had a bug on release where one icon is missing from light theme and using light theme crashes on open. We already have a fix relese here: https://github.com/jliljebl/flowblade/releases/tag/v2.4.0.1-fix_release

You can **fix this on your system** in 2 ways.

First by copying icon 
*<install_folder>/Flowblade/res/darktheme/compositor_icon.png*   into
*<install_folder>/Flowblade/res/img/compositor_icon.png* 

Second by deleting file */HOME$/.config/flowblade/prefs* and *not selecting light theme* after that.

First one is obivously a better solution.

It would be best to get your distribution to update Flowblade into release fix:  https://github.com/jliljebl/flowblade/releases/tag/v2.4.0.1-fix_release
