### ISSUE TITLE
can't move project to different user/machine/directory

### ISSUE THREAD

**Issue by bfristensky** [jliljebl/flowblade-forum#61]
I tried creating a tar archive of a directory containing all the files for a flowblade project, uploading the archive to a different user account on a different machine, and opening the project on the new machine. Flowblade popped up a progress window saying that it was "unpickling", and the project never opened.
Here are the relevant messages:
```
Loading BLASTsearch.flb, SAVEFILE_VERSION: 5
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/share/flowblade/Flowblade/projectaction.py", line 84, in run
    project = persistance.load_project(self.filename)
  File "/usr/share/flowblade/Flowblade/persistance.py", line 308, in load_project
    raise ProjectProfileNotFoundError(project.profile_desc)
ProjectProfileNotFoundError: '2.5K QHD 1440p 30 fps'
```
A bit of snooping around shows that the .flb file contains fully qualified paths, rather than relative paths. This would mean that the video clips read by flowblade wouldn't be found. As well, I notice that there is a $HOME/.flowblade directory which may also have fully qualified paths.
I next tried editing the .flb file to replace all occurrences of the old home directory eg. /home/me
with the new home directory eg. /home/myself.  No change.

Does this mean that a project will always be wedded to a single directory and user on a single machine, or is there a way to make projects portable between machines?

**Comment by jliljebl** [comment]
> Does this mean that a project will always be wedded to a single directory and user on a single machine, or is there a way to make projects portable between machines?

When project is opened it looks for media items in relative paths to project file (same folder and subfolders) if absolute path does not have the file available.

So files being saved with absolute paths is not the problem here.

Your problem is the Project profile file which is not found on the new machine so the Profile is not available.

Don't know why the file is not available, is it this one: https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/Flowblade/res/profiles/qhd_1440p_30

If you can save it in your installation's subfolder folder *../res/profiles* in your new machine maybe that can help. You do obviously need to have Flowblade installed on new machine too to make the profile file available.

Note that earlier version s used $HOME/.flowblade directory but since version 2.2 we use XDG folder locations which are defined by the system, this could have some effect here.

The project portability is basically *best effort* but we will always try to improve on this.
